### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu

### ISSUE THREAD

**Issue by cg904699855** [DongChen06/MACACC#1]
![image](https://github.com/user-attachments/assets/2dcfa6d8-41ad-4022-9a41-ff2ec275ec17)

![image](https://github.com/user-attachments/assets/2e322256-e09a-42a0-9494-eba66990ba4b)

Hi！Thank you very much for your sharing, my current research needs to use multi-agent reinforcement learning, but when I uncomment and try to run the code on the gpu, the program still reports errors.
![image](https://github.com/user-attachments/assets/d99a95fc-6783-414a-a22b-44692c97dcfd)

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu

How do I solve this?

**Comment by DongChen06** [comment]
Hi, you may put all your data on the CPU. There is no speed up with GPU

**Comment by cg904699855** [comment]
ok，thanks for your reply！
